site_name: Introduction to NGS ATAC-seq data analysis 

nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Day1:
      - 00 Connect to server : days/00_connect_to_server.md
      - 01 Filter bam files : days/01_filter_bam_files.md  
      - 02 QC post alignment : days/02_QC_post_alignment.md
      - 03 Peak calling : days/03_peak_calling.md
      - 04 Build consensus peak set : days/04_build_consensus_peak_set.md
      - 05 Quantify peaks : days/05_quantify_peaks.md
      - 06 Differential accessibility analysis : days/06_differential_accessibility_analysis.md
      - 07 Annotate peaks : days/07_annotate_peaks.md

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg

# Repository
repo_name: sib-swiss/gh-pages-training
repo_url: https://github.com/sib-swiss/gh-pages-training

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
